# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task/v1/task.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'task/v1/task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12task/v1/task.proto\x12\x07task.v1\"\\\n\x12ProcessTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\ttask_type\x18\x02 \x01(\t\x12\x10\n\x08raw_text\x18\x03 \x01(\t\x12\x10\n\x08trace_id\x18\x04 \x01(\t\"{\n\x13ProcessTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x17\n\x0fnormalized_text\x18\x03 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x04 \x01(\x03\x12\x15\n\rerror_message\x18\x05 \x01(\t2Y\n\rTaskProcessor\x12H\n\x0bProcessTask\x12\x1b.task.v1.ProcessTaskRequest\x1a\x1c.task.v1.ProcessTaskResponseB\x1fZ\x1drelayops/proto/task/v1;taskv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task.v1.task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035relayops/proto/task/v1;taskv1'
  _globals['_PROCESSTASKREQUEST']._serialized_start=31
  _globals['_PROCESSTASKREQUEST']._serialized_end=123
  _globals['_PROCESSTASKRESPONSE']._serialized_start=125
  _globals['_PROCESSTASKRESPONSE']._serialized_end=248
  _globals['_TASKPROCESSOR']._serialized_start=250
  _globals['_TASKPROCESSOR']._serialized_end=339
# @@protoc_insertion_point(module_scope)
